version: '3.8'

services:
  mysql:
    image: yobasystems/alpine-mariadb
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: website
      MYSQL_USER: website
      MYSQL_PASSWORD: website_password
    networks:
      - net-bridge

  php:
    build:
      context: ./docker
      dockerfile: php-fpm.dockerfile
    volumes:
      - ./:/var/www/
    networks:
      - net-bridge
    environment:
      # Enable xdebug remote
      XDEBUG_CONFIG: discover_client_host=On
      XDEBUG_MODE: debug

  nginx:
    image: nginx:alpine
    ports:
       - 8080:80
    volumes_from:
      - php
    volumes:
      - ./docker/site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - net-bridge

networks:
  net-bridge:
