version: '3.8'

services:
  mysql:
    extends:
      file: docker-compose.base.yml
      service: mysql

  rabbitmq:
    extends:
      file: docker-compose.base.yml
      service: rabbitmq

  mercure:
    extends:
      file: docker-compose.base.yml
      service: mercure

  php:
    extends:
      file: docker-compose.base.yml
      service: php
    volumes:
      - appData:/var/www

  php-worker:
    extends:
      file: docker-compose.base.yml
      service: php-worker
    depends_on:
      - rabbitmq

  nginx:
    extends:
      file: docker-compose.base.yml
      service: nginx
    volumes_from:
      - php

  maildev:
    extends:
      file: docker-compose.base.yml
      service: maildev

networks:
  net-bridge:

volumes:
  caddy_data:
  caddy_config:
  appData:
