version: '3.8'

services:
  mysql:
    image: yobasystems/alpine-mariadb
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql-fixtures/:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: website
      MYSQL_USER: website
      MYSQL_PASSWORD: website_password
    networks:
      - net-bridge

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 15672:15672
    networks:
      - net-bridge
    environment:
      RABBITMQ_DEFAULT_USER: website
      RABBITMQ_DEFAULT_PASS: website_password

  php: &php-fpm
    build:
      context: .
      dockerfile: docker/php-fpm.dockerfile
    volumes:
      - ./:/var/www/
    networks:
      - net-bridge
    environment:
      # Enable xdebug remote
      XDEBUG_CONFIG: discover_client_host=On
      XDEBUG_MODE: debug
      SYMFONY_DEPRECATIONS_HELPER: "quiet[]=indirect&quiet[]=other"

  # PHP worker run the consumers for RabbitMQ queue
  php-worker:
    <<: *php-fpm
    restart: always
    command: sh -c "sleep 2 && bin/console messenger:consume async --memory-limit=128M"
    depends_on:
      - rabbitmq
    environment:
      # Disable xdebug
      XDEBUG_CONFIG: discover_client_host=Off
      XDEBUG_MODE: "off"

  nginx:
    image: nginx:alpine
    ports:
      - 8080:80
    volumes_from:
      - php
    volumes:
      - ./docker/site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - net-bridge

  maildev:
    image: maildev/maildev
    command: "bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS"
    ports:
      - 1080:80
    networks:
      - net-bridge

networks:
  net-bridge:

volumes:
  appData:
    driver: local
